// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PcxRDjbZ6HlRRKbqTRw6wUeeZgj46Ew',
    appId: '1:863085466179:web:42558cda740c08f67ffaf6',
    messagingSenderId: '863085466179',
    projectId: 'helping-app-98862',
    authDomain: 'helping-app-98862.firebaseapp.com',
    storageBucket: 'helping-app-98862.appspot.com',
    measurementId: 'G-9RDQ729P51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBav0gx7287dlyIFrZQPJ8B-ip4kOUfsaE',
    appId: '1:863085466179:android:7342b4708d94e32d7ffaf6',
    messagingSenderId: '863085466179',
    projectId: 'helping-app-98862',
    storageBucket: 'helping-app-98862.appspot.com',
  );
}
